# Generated by Django 5.1.7 on 2025-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Vue', 'Vue'), ('Django', 'Django'), ('HTML_CSS', 'HTML & CSS'), ('JS', 'JavaScript'), ('TS', 'TypeScript'), ('Algorithms', 'Algorithms and Data Structures')], default='Vue', max_length=50),
            preserve_default=False,
        ),
    ]
